const Router = require('express');

const routes = Router();
const portBot = process.env.PORTBOT

const InitiatorController = require('../controllers/InitiatorController') ;
const RestartController = require('../controllers/RestartController') ;
const RefreshbotController = require('../controllers/RefreshbotController') ;
const AtualizaentradaController = require('../controllers/AtualizaentradaController') ;
const FinalizaticketController = require('../controllers/FinalizaticketController') ;
const SendAudioController = require('../controllers/SendAudioController') ;
const SendFileController = require('../controllers/SendFileController') ;
const NewTicketController = require('../controllers/NewTicketController') ;
const UserChatController = require('../controllers/UserChatController') ;
const LogoutController = require('../controllers/LogoutController') ;
const ResetBotController = require('../controllers/ResetBotController') ;
const NewListController = require('../controllers/NewListController') ;
const NewStatusController = require('../controllers/NewStatusController') ;
const LoggedController = require('../controllers/LoggedController') ;
const TransferChatController = require('../controllers/TransferChatController') ;
const GetUseridController = require('../controllers/GetUseridController') ;
const BlockUserController = require('../controllers/BlockUserController') ;
const UnblockUserController = require('../controllers/UnblockUserController') ;
const GetUserPicController = require('../controllers/GetUserPicController') ;
const NewChatController = require('../controllers/NewChatController') ;
const NewRequestController = require('../controllers/NewRequestController') ;
const SendController = require('../controllers/SendController') ;
const RemoveController = require('../controllers/RemoveController') ;
const PowerOnController = require('../controllers/PowerOnController') ;

const initiatorController = new InitiatorController();
const restartController = new RestartController();
const refreshbotController = new RefreshbotController();
const atualizaentradaController = new AtualizaentradaController();
const finalizaticketController = new FinalizaticketController();
const sendAudioController = new SendAudioController();
const sendFileController = new SendFileController();
const newTicketController = new NewTicketController();
const userChatController = new UserChatController();
const logoutController = new LogoutController();
const resetBotController = new ResetBotController();
const newListController = new NewListController();
const newStatusController = new NewStatusController();
const loggedController = new LoggedController();
const transferChatController = new TransferChatController();
const getUseridController = new GetUseridController();
const blockUserController = new BlockUserController();
const unblockUserController = new UnblockUserController();
const getUserPicController = new GetUserPicController();
const newChatController = new NewChatController();
const newRequestController = new NewRequestController();
const sendController = new SendController();
const removeController = new RemoveController();
const powerOnController = new PowerOnController();

routes.post('/' + portBot + '/inicializador', initiatorController.create);
routes.post('/' + portBot + '/restart', restartController.create);
routes.post('/' + portBot + '/refreshbot', refreshbotController.create);
routes.post('/' + portBot + '/atualizaentrada', atualizaentradaController.create);
routes.post('/' + portBot + '/finalizaticket', finalizaticketController.create);
routes.post('/' + portBot + '/sendaudio', sendAudioController.create);
routes.post('/' + portBot + '/sendfile', sendFileController.create);
routes.post('/' + portBot + '/newticket', newTicketController.create);
routes.post('/' + portBot + '/userchat', userChatController.create);
routes.post('/' + portBot + '/logout', logoutController.create);
routes.post('/' + portBot + '/resetbot', resetBotController.create);
routes.post('/' + portBot + '/newlist', newListController.create);
routes.post('/' + portBot + '/newstatus', newStatusController.create);
routes.post('/' + portBot + '/logged', loggedController.create);
routes.post('/' + portBot + '/transferchat', transferChatController.create);
routes.post('/' + portBot + '/getuserid', getUseridController.create);
routes.post('/' + portBot + '/blockuser', blockUserController.create);
routes.post('/' + portBot + '/unblockuser', unblockUserController.create);
routes.post('/' + portBot + '/getuserpic', getUserPicController.create);
routes.post('/' + portBot + '/newchat', newChatController.create);
routes.post('/' + portBot + '/newrequest', newRequestController.create);
routes.post('/' + portBot + '/send', sendController.create);
routes.post('/3000/remove', removeController.create);
routes.post('/3000/poweron', powerOnController.create);

module.exports = routes;
